### ISSUE TITLE
different vjoy interface?

### ISSUE THREAD

**Issue by IronFox** [raptorswing/MouseToJoystick#11]
Hi there,
Is it possible to use a vjoy interface other than 1?
I'm trying to run multiple virtual joysticks at the same time.

Cheers,
Stefan

**Comment by raptorswing** [comment]
Hello. Sorry for the delay. I've created a new beta version, available [here](https://github.com/raptorswing/MouseToJoystick/releases/tag/2.0-beta), which has this capability. I hope it will help you.
