### ISSUE TITLE
Two mouses input

### ISSUE THREAD

**Issue by kazumasan144** [raptorswing/MouseToJoystick#15]
Dear Sir,

I had an idea to try to modify your program after i tested your program but I am not sure if it is possible as many told me it is not.
I have 3 mouses. I like your program to read the 2nd and 3rd mouse inputs (axes,clicks) simultaneously and feed to 1st vJoy joystick and 2nd vJoyStick. May I please ask if it is possible?

Thank you for your time to read this!

**Comment by kazumasan144** [comment]
If it is possible sir, I hope to develop it under your guidance. I will pay for your time if you wish.

**Comment by raptorswing** [comment]
Hello,

It would be possible to make a program that does what you've described, but it would work a little bit differently from this one. This program gets consolidated mouse input from Windows and can't tell how many mice are connected and what their individual inputs are - that information is abstracted away by Windows.

The program you've described needs to get individual input from multiple mice. I know that Windows has an API somewhere for getting lower-level, per-device mouse input data but I don't remember where it is or what it's called and I've never used it.

I don't have time to investigate or help further at this time, but I hope that this helps a little bit.
