### ISSUE TITLE
how to compile

### ISSUE THREAD

**Issue by rob19841** [raptorswing/MouseToJoystick#4]
how do i get this working i don't know how to compile a project i have attempted to compile it in visual studio but i end up getting a lot of errors. im not much of a programmer but i really need a feature like this

**Comment by raptorswing** [comment]
Hi,

There are some pre-compiled binaries available for download [here](https://github.com/raptorswing/MouseToJoystick/releases). Hopefully one of those will work for you.

Thanks.
