### ISSUE TITLE
Using MouseToJoystick for x-wing Alliance

### ISSUE THREAD

**Issue by th0rin0ak** [raptorswing/MouseToJoystick#5]
Hello,

Thank you for this wonderful program. I have both the 32-bit and 64-bit versions on my computer, and both work well. However, they do not seem to work in conjunction with my x-wing alliance game. The game opens like usual, however when I try to play the first mission, it simply doesn't load when MouseToJoystick is running in the background. If I close the program, the game runs fine. I have also tried starting MouseToJoystick after I have started playing x-wing alliance, and it crashes immediately. Do you know of any fixes to make this program work with x-wing alliance? Thank you.

**Comment by raptorswing** [comment]
Hi,

Sorry you're having trouble. I have not encountered this and am not sure what the problem could be. I don't have a copy of X-Wing Alliance to test it with, either :frowning:

**Comment by raptorswing** [comment]
I've rewritten this tool. I'm not sure that it will solve this particular issue, but please feel free to give it a try [here](https://github.com/raptorswing/MouseToJoystick/releases/tag/2.0-beta).
