### ISSUE TITLE
How to donate

### ISSUE THREAD

**Issue by mmogithub** [raptorswing/MouseToJoystick#8]
I think you deserve a beer for this great job.
**Can I make a paypal donation?**
Anyway, thank you for your great "mousetojoystick", I was able to enjoy many years later (I bought the original in 1994) of the game in the remastered version with my little mouse as controller.
Thank you

**Comment by raptorswing** [comment]
Thank you for your kind words. I'm very glad that this little project was helpful for you. 

Unfortunately, I shuttered my PayPal account a few years ago. Really, saying thanks is enough, but if you are so inclined, I can accept BitCoin at 1AM26ucGYxhf2WSnaEsrUwpLzkWcEZWigK.

**Comment by mmogithub** [comment]
Dear raptorswing, 
Sorry, I don't have access to pay with BitCoins.
What a pity.
In any case, indeed, your piece of software is a beauty that allows me to enjoy many years after a great game with my mouse when I'm traveling with my laptop away from home.
So, yes, thank you very much for your generous effort and dedication.

Kind regards

P. S. - I'll open another ticket with a couple of IMPROVEMENT TIPS in case you can spend some time.
